name: Testes Automatizados

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'corretto'

      - name: Compilar o projeto
        run: mvn compile

      - name: Executar testes
        run: mvn verify

      - name: Enviar cobertura para Codecov
        uses: codecov/codecov-action@v3
        with:
          files: target/site/jacoco/jacoco.xml
