name: Testes Automatizados

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'correto'

      - name: Compilar o projeto
        run: mvn compile

      - name: Executar testes
        run: mvn test
